---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: build-tool
spec:
  description: >-
    This Task can be used to run a Maven build.
  workspaces:
    - name: output
    - name: maven-settings
    - name: maven-m2
    - name: sonarqube-auth
      optional: true
  params:
    - name: MAVEN_IMAGE
      type: string
      description: Maven base image
      default: registry.access.redhat.com/ubi8/openjdk-17:latest
    - name: GOALS
      description: maven goals to run
      type: string
    - name: MAVEN_BUILD_OPTS
      description: maven build options
      type: string
    - name: WORK_DIRECTORY
      description: Directory to start build in (handle multiple branches)
      type: string
  results:
    - name: VERSION
      description: Version of application
  steps:
    - name: mvn-goals
      image: $(params.MAVEN_IMAGE)
      workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
      script: |
         #!/usr/bin/bash
         set +x
         test -f $(workspaces.sonarqube-auth.path) || export EXTRA_ARGS="-Dsonar.login=$(cat $(workspaces.sonarqube-auth.path)/username) -Dsonar.password=$(cat $(workspaces.sonarqube-auth.path)/password)"
         /usr/bin/mvn -s $(workspaces.maven-settings.path)/settings.xml $(params.GOALS) $(params.MAVEN_BUILD_OPTS) ${EXTRA_ARGS}
    - name: get-app-version
      image: $(params.MAVEN_IMAGE)
      workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
      command: ["/bin/sh", "-c"]
      args:
        - echo -n $(mvn -s $(workspaces.maven-settings.path)/settings.xml help:evaluate -Dexpression=project.version -q -DforceStdout) | xargs echo -n | tee $(results.VERSION.path)
