---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitlab-webhook
  labels:
    app: gitlab
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: gitlab-trigger-binding
    interceptors:
    - params:
      - name: filter
        value: (header.match('X-Gitlab-Event', 'Push Hook') && body.project.path_with_namespace
          == '{{ .Values.team }}/pet-battle-api' && body.ref.split('/')[2] == 'main')
      - name: overlays
        value:
        - expression: body.checkout_sha.truncate(7)
          key: truncated_sha
        - expression: body.ref.split('/')[2]
          key: branch_name
        - expression: body.repository.name
          key: app_of_apps_key
      ref:
        kind: ClusterInterceptor
        name: cel
    name: pet-battle-api-webhook-all-branches
    template:
      ref: pet-battle-api-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: gitlab-webhook
spec:
  port:
    targetPort: http-listener
  to:
    kind: 'Service'
    name: el-gitlab-webhook
    weight: 100
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge