name: tl500-tech-exercise-test-build-push
on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - tests/
      - .github/workflows/tl500-tech-exercise-test-build-push.yaml
jobs:
  build:
    env:
      context: tests/container
      image_name: tl500-tech-exercise-test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Get image tags
        id: image_tags
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
           # exposes variable VERSION
          source ${context}/VERSION
          TAGS=('latest')
          if [ "${VERSION}" ] && [ "${VERSION}" != "latest" ]; then
              TAGS+=("${VERSION}")
          fi
          echo "${TAGS[*]}"
      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2.6
        with:
          context: ${{ env.context }}
          dockerfiles: |
            ./${{ env.context }}/Containerfile
          image: ${{ env.image_name }}
          tags: "${{ steps.image_tags.outputs.IMAGE_TAGS }}"
      - name: Push to Quay
        id: push_to_quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          registry: ${{ secrets.REGISTRY_URI }}/${{ secrets.REGISTRY_REPOSITORY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          tags: ${{ steps.build_image.outputs.tags }}
